
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async greet(name: string) : Promise<string> {
    return await TAURI_INVOKE("greet", { name });
},
async experimentCreate(name: string) : Promise<Result<Experiment, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("experiment_create", { name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async experimentDelete(experimentId: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("experiment_delete", { experimentId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async experimentList() : Promise<Result<Experiment[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("experiment_list") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async experimentSetActive(experimentId: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("experiment_set_active", { experimentId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async exportCsvExperiments(outputDirectory: string, experimentIds: number[] | null) : Promise<Result<ExportSummary, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("export_csv_experiments", { outputDirectory, experimentIds }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async exportExcelExperiments(outputDirectory: string, experimentIds: number[] | null) : Promise<Result<ExportSummary, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("export_excel_experiments", { outputDirectory, experimentIds }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async historyLoadExperiment(experimentId: number, maxRows: number) : Promise<Result<HistorySnapshot, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("history_load_experiment", { experimentId, maxRows }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async serialSetPort(port: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("serial_set_port", { port }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async serialConnect() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("serial_connect") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async serialDisconnect() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("serial_disconnect") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async serialStatus() : Promise<Result<ConnectionStatus, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("serial_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async serialListPorts() : Promise<Result<string[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("serial_list_ports") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async serialSend(request: SerialRequest, timeoutMs: number | null) : Promise<Result<SerialResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("serial_send", { request, timeoutMs }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async subscribeSensorFrames(channel: TAURI_CHANNEL<SensorFrame>) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("subscribe_sensor_frames", { channel }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async subscribeEnvironmentFrames(channel: TAURI_CHANNEL<EnvironmentFrame>) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("subscribe_environment_frames", { channel }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type ConnectionStatus = "Disconnected" | "Connecting" | { Connected: { port: string } }
export type EnvironmentFrame = { wellTempC: number; ambientTempRaw: number; ambientPressureRaw: number; ambientHumidityRaw: number }
export type EnvironmentHistoryRow = { capturedAtMs: number; wellTemperatureC: number; ambientTemperatureC: number; ambientPressurePa: number; ambientHumidityPct: number }
export type Experiment = { id: number | null; name: string }
export type ExportSummary = { experimentsExported: number; filesWritten: number }
export type HistorySnapshot = { environment: EnvironmentHistoryRow[]; readings: WellReadingHistoryRow[] }
export type LedAction = "Off" | "On" | "Toggle" | "SetBrightness"
export type SensorFrame = { values: number[]; wavelength: number }
export type SerialRequest = "Ping" | "SystemStatus" | "EnvironmentInfo" | "PhotosensorResults" | { SetLedState: { wavelength: number; action: LedAction; brightness: number } }
export type SerialResponse = "Ping" | { SystemStatus: { fw: number; state: number; uptime: number } } | { EnvironmentInfo: { well_temp: number; ambient_temp: number; ambient_pressure: number; ambient_humidity: number } } | { PhotosensorResults: { wavelength: number; values: number[] } } | { TelecommandAck: { tc_id: number; tc_result: number } } | { Error: { code: number } } | { Unknown: { frame_id: number; payload: number[] } }
export type TAURI_CHANNEL<TSend> = null
export type WellReadingHistoryRow = { capturedAtMs: number; wavelengthNm: number; well1Intensity: number; well2Intensity: number; well3Intensity: number; well4Intensity: number; well5Intensity: number; well6Intensity: number; well7Intensity: number; well8Intensity: number; well9Intensity: number; well10Intensity: number; well11Intensity: number; well12Intensity: number; well13Intensity: number; well14Intensity: number }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
